[package]
name = "o_spl_token"
version = "0.1.0"
edition = "2021"
rust-version = "1.84"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
v_transfer_no_signer = []
v_transfer_no_mint_check = []
v_mint_to_no_signer = []
v_mint_to_no_mint_check = []
no-entrypoint = []
test-sbf = []

[lints.rust]
unexpected_cfgs = { level = "allow" }

[dependencies]
arrayref = "0.3.9"
bytemuck = "1.20.0"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.3"
solana-account-info = "2.2.0"
solana-cpi = "2.2.0"
solana-decode-error = "2.2.0"
solana-instruction = "2.2.0"
solana-msg = "2.2.0"
solana-program-entrypoint = "2.2.0"
solana-program-error = "2.2.0"
solana-program-memory = "2.2.0"
solana-program-option = "2.2.0"
solana-program-pack = "2.2.0"
solana-pubkey = { version = "2.2.0", features = ["bytemuck"] }
solana-rent = "2.2.0"
solana-sdk-ids = "2.2.0"
solana-sysvar = { version = "2.2.0", features = ["bincode"] }
thiserror = "2.0"
