[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
indexmap = "2"
serde_json = { version = "1", features = ["preserve_order"] }
miniz_oxide = "0.8"
regex = { version = "1", default-features = false, features = ["std", "unicode-case"] }
sbpf-elf = { path = "crates/sbpf-elf" }
sbpf-ir = { path = "crates/sbpf-ir" }
sbpf-program = { path = "crates/sbpf-program" }
sbpf-dataflow = { path = "crates/sbpf-dataflow" }
sbpf-opt = { path = "crates/sbpf-opt" }
sbpf-struct = { path = "crates/sbpf-struct" }
sbpf-print = { path = "crates/sbpf-print" }
sbpf-exec = { path = "crates/sbpf-exec" }
sbpf-read = { path = "crates/sbpf-read" }
sbpf-lib = { path = "crates/sbpf-lib" }

[profile.release]
codegen-units = 1
debug = false
