[package]
name = "a_oracle"
version = "0.1.0"
edition = "2021"
rust-version = "1.84"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
v_ungated = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = []
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = { workspace = true }
bytemuck = { version = "1", features = ["derive", "min_const_generics"] }
