[package]
name = "sbpf-print"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
serde_json.workspace = true
sbpf-elf.workspace = true
sbpf-ir.workspace = true
sbpf-program.workspace = true
sbpf-dataflow.workspace = true
sbpf-opt.workspace = true
sbpf-struct.workspace = true
memchr.workspace = true
