[package]
name = "sbpf-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "sbpf-decompile"
path = "src/main.rs"

[dependencies]
serde_json.workspace = true
miniz_oxide.workspace = true
sbpf-ir.workspace = true
sbpf-program.workspace = true
sbpf-print.workspace = true
sbpf-read.workspace = true
mimalloc = { version = "0.1", default-features = false }
ureq = { version = "3", default-features = false, features = ["rustls"] }

[[bin]]
name = "sbpf-selector"
path = "src/bin/sbpf-selector.rs"
