[package]
name = "sbpf-lib"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
serde_json.workspace = true
regex.workspace = true
sbpf-elf.workspace = true
sbpf-ir.workspace = true
sbpf-program.workspace = true
sbpf-opt.workspace = true
sbpf-print.workspace = true
sbpf-exec.workspace = true
