[package]
name = "sbpf-read"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
serde_json.workspace = true
miniz_oxide.workspace = true
regex.workspace = true
memchr = "2"
sbpf-elf.workspace = true
sbpf-ir.workspace = true
sbpf-program.workspace = true
sbpf-dataflow.workspace = true
sbpf-opt.workspace = true
sbpf-struct.workspace = true
sbpf-print.workspace = true
sbpf-exec.workspace = true
sbpf-lib.workspace = true
